name: ci

on:
  push:
  pull_request:

jobs:
  core:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
      - name: Configure
        run: cmake -S . -B build -G Ninja -DPHOTOSLOP_BUILD_APP=OFF -DPHOTOSLOP_BUILD_TESTS=ON
      - name: Build
        run: cmake --build build
      - name: Test
        run: ctest --test-dir build --output-on-failure
